In [34]:
%pip install bs4
%pip install pandas

Requirement already satisfied: bs4 in /Users/blakeenyart/programming/projects/sandbox/data-engineering-practice/.venv/lib/python3.11/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /Users/blakeenyart/programming/projects/sandbox/data-engineering-practice/.venv/lib/python3.11/site-packages (from bs4) (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /Users/blakeenyart/programming/projects/sandbox/data-engineering-practice/.venv/lib/python3.11/site-packages (from beautifulsoup4->bs4) (2.4)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
from bs4 import BeautifulSoup
import requests

In [4]:
url = 'https://www.ncei.noaa.gov/data/local-climatological-data/access/2021/'
response = requests.get(url)

In [5]:
html_doc = response.text
soup = BeautifulSoup(html_doc, 'html.parser')
links = soup.find_all('tr')

In [7]:
csv_link = None
for link in links:
    for child in link.children:
        if child.get_text(strip=True) == '2022-02-07 14:03':
            csv_link = link.find('a').get('href')
            break

In [22]:
assert csv_link
full_url = url + csv_link

csv_response = requests.get(full_url)

In [9]:
import pandas as pd

with open('test.csv', 'w') as fd:
  fd.write(csv_response.text)

In [11]:
with open('test.csv', 'r') as fd:
    df = pd.read_csv(fd, dtype=object)

In [21]:
# invalid values placed in the HourlyDryBulbTemperature column
df['HourlyDryBulbTemperature'] = pd.to_numeric(df['HourlyDryBulbTemperature'],errors='coerce')
max_temp = df['HourlyDryBulbTemperature'].max()

df[df['HourlyDryBulbTemperature'] == max_temp]

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,SOURCE,HourlyAltimeterSetting,HourlyDewPointTemperature,...,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupElevation,BackupEquipment,BackupLatitude,BackupLongitude,BackupName,WindEquipmentChangeDate
7274,A0002453848,2021-07-26T12:53:00,30.51195,-86.95406,34.0,"CHOCTAW NAVAL OUTLYING FIELD MILTON, FL US",FM-15,6,29.96,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-22
7275,A0002453848,2021-07-26T13:53:00,30.51195,-86.95406,34.0,"CHOCTAW NAVAL OUTLYING FIELD MILTON, FL US",FM-15,6,29.94,69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-22
7299,A0002453848,2021-07-27T12:53:00,30.51195,-86.95406,34.0,"CHOCTAW NAVAL OUTLYING FIELD MILTON, FL US",FM-15,6,29.99,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-22
7300,A0002453848,2021-07-27T13:53:00,30.51195,-86.95406,34.0,"CHOCTAW NAVAL OUTLYING FIELD MILTON, FL US",FM-15,6,29.96,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-22
7301,A0002453848,2021-07-27T14:39:00,30.51195,-86.95406,34.0,"CHOCTAW NAVAL OUTLYING FIELD MILTON, FL US",FM-16,6,29.96,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-22
7372,A0002453848,2021-07-29T12:53:00,30.51195,-86.95406,34.0,"CHOCTAW NAVAL OUTLYING FIELD MILTON, FL US",FM-15,6,30.01,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-22